### PR TITLE
Create program-addresses.md

### PR DESCRIPTION
**Pull request by TomintheToon**
Table extracted from Dual DAO page and supplemented with additional addresses.

### CODE REVIEW

**Comment by TomintheToon** [comment]
@DonDuala Did I do this right?

**Comment by jlkramer16** [comment]
You'll need to add the page reference here too https://github.com/TomintheToon/docs/blob/TomintheToon-patch-2/SUMMARY.md

Try creating a gitbook account and sync-ing your repo to the workspace. Then you can edit in a "no code" manner and see how it will look on the real docs page

**Comment by TomintheToon** [comment]
> 

Added the page ref.

Will check out gitbook, thanks for your help!

**Comment by jlkramer16** [comment]
You should rebase your branch to the main before making changes. This is difficult to review. Shouldn't be 42 files changes

**Pull request closed without merging**
